- name: variables from args
  hosts: local
  connection: local
  tasks:
    - name: print the course info
      ansible.builtin.debug:
        msg: "course info is: {{COURSE}} duration is: {{DURATION}} trainer is {{TRAINER}}"
